main: manager.Manager
name: dasGesetz
version: 3.7.6
api-version: 1.21
author: MokkaGnom
description: Das Gesetz. Timber, EasyFarming, DeathChest, BlockLock, Home, Ping
commands:
  dgManager:
    description: Aktiviert/Deaktiviert das sub-Plugin
    usage: /dgManager <plugin> <0/1>
    permission: dg.dgManagerPermission
    aliases:
      - dgm
  dasGesetz:
    description: Gibt das Gesetz im Chat aus
    usage: /DasGesetz [Artikel]
    permission: dg.dasGesetzPermission
    aliases:
      - dg
  weatherClear:
    description: Setzt das Wetter auf klar (gleich wie der Standard-Befehl aus mc)
    usage: /WeatherClear
    permission: dg.weatherClearPermission
    aliases:
      - wc
  coords:
    description: Gibt die aktuellen Koordinaten des Spielers
    usage: /Coords <Player>
    permission: dg.coordsPermission
    aliases:
      - co
  blockLock:
    description: Verwaltet einen abschließbaren Block
    usage: /blockLock <lock/unlock/addFriend/removeFriend/addGlobalFriend/removeGlobalFriend/listFriends/showMenu>
    permission: dg.blockLockPermission
    aliases:
      - bl
  deathChest:
    description: Zeigt alle aktiven DeathChests (des Spielers) an
    usage: /deathChest list
    permission: dg.deathChestPermission
    aliases:
      - dc
  home:
    description: Verwalten von Home-Punkten
    usage: /home <tp/add/remove/list> <homeName>
    permission: dg.homePermission
    aliases:
      - h
  ping:
    description: Setzt die Farbe des Pings
    usage: /ping setColor <colorcode>
    permission: dg.pingPermission
    aliases:
      - p
  blockLogger:
    description: Verwaltet geloggte Blöcke
    usage: /blockLogger <list/add/remove> <material>
    permission: dg.blockLoggerPerm
    aliases:
      - blog
  prefix:
    description: Verwaltet prefixe
    usage: /prefix <list/add/remove/create/delete>
    permission: dg.prefixUsePermission
  villagerCreator:
    description: Zum verwalten von Villager erstellen
    usage: /villagerCreator <remove>
    permission: dg.createVillagerPermission
permissions:
  dg.dgManagerPermission:
    description: Allows a Player to use the Manager
    default: op
  dg.dasGesetzPermission:
    description: Allows a Player to use the Law command
    default: true
  dg.weatherClearPermission:
    description: Allows a Player to use the WeaterClear command
    default: true
  dg.coordsPermission:
    description: Allows a Player to use the Coords command
    default: op
  dg.timberPermission:
    description: Allows a Player to use timber
    default: true
  dg.deathChestPermission:
    description: Allows a Player to use/create deathChest
    default: true
  dg.deathChestByPassPermission:
    description: Allows a Player to use deathChest from everyone
    default: op
  dg.blockLockPermission:
    description: Allows a Player to use/create lockable chests, etc.
    default: true
  dg.blockLockByPassPermission:
    description: Allows a Player to use/create lockable chests, etc. from everyone
    default: op
  dg.homePermission:
    description: Allows a Player to use/create homes
    default: true
  dg.easyFarmingPermission:
    description: Allows a Player to use the plugin
    default: true
  dg.pingPermission:
    description: Allows a Player to use the ping
    default: true
  dg.blockLoggerPerm:
    description: Allows a Player to add/remove/list logged blocks
    default: op
  dg.createVillagerPermission:
    description: Allows a Player to spawn a Villager by sneaking with another player
    default: true
  dg.prefixUsePermission:
    description: Allows a Player to use the prefix commands
    default: true
  dg.prefixAdminPermission:
    description: Allows a Player to use admin prefix commands
    default: op